### ISSUE TITLE
Build DeepLearnJS on Windows

### ISSUE THREAD

**Issue by Yagun** [PAIR-code/deeplearnjs#534]
Build script
./scripts/build-standalone.sh
does not work on Windows. The following string throws an error:
yarn make-version && \

Console log:

yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 3.09s.
yarn run v1.3.2
$ ./scripts/make-version
'.\scripts\make-version' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: ENOENT: no such file or directory, open 'D:\WORK\deeplearnjs\dist\deeplearn.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at read_file (D:\WORK\deeplearnjs\node_modules\uglify-js\bin\uglifyjs:306:19)
    at D:\WORK\deeplearnjs\node_modules\uglify-js\bin\uglifyjs:153:37
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\WORK\deeplearnjs\node_modules\uglify-js\bin\uglifyjs:152:31)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)

**Comment by dsmilkov** [comment]
@nkreeger Any ideas since you have a windows machine? Thanks!
