### ISSUE TITLE
ReferenceError: name is not defined

### ISSUE THREAD

**Issue by rilut** [PAIR-code/deeplearnjs#811]
```ts
import { Array1D, Array2D, ENV, Scalar } from 'deeplearn';
import * as dl from 'deeplearn';
import { TensorLike1D } from 'deeplearn/dist/types';

const mse = (y_pred, y_true) => dl.scalar(y_true).sub(y_pred).square();
const learningRate = 0.01;
const optimizer = dl.train.sgd(learningRate);

//
const num_vocab = 5000;
const embed_dim = 300;
const embed_W = dl.variable(dl.randomNormal([4, embed_dim], 0, 0.1) as dl.Tensor2D, true, "embed_W");

//
function forward(input: TensorLike1D) {
  const x = dl.tensor1d(input)
  const Wx = dl.gather(embed_W, x)
  const y = dl.mean(Wx, 1)
  return y;
}


async function train(xs: number[][], ys: number[], num_epoch: number, done: Function) {
  try {
    for (let epoch = 0; epoch < num_epoch; epoch++) {
      for (let row = 0; row < xs.length; row++) {
        // Backward
        optimizer.minimize(() => {
          const x = xs[row]
          const pred = forward(x);
          const loss = mse(pred, ys[row]);
          return loss;
        });
      }
    }

    done();
  } catch (error) {
    console.error(error)
  }
}

function predict(xs, ys) {
  const predictedYs = xs.map(forward);
  console.log('y_true: ', ys);
  console.log('y_pred: ', predictedYs.map((p) => p.dataSync()[0]));
}

const data = {
  xs: [[0, 1, 2, 3], [0, 1, 2, 3]],
  ys: [1, 0]
};


// Predict
// predict(data.xs, data.ys);

// Train
train(data.xs, data.ys, 5, () => { /* predict(data.xs, data.ys); */ });

```
I can to do the prediction. But if I run the training with`$ ts-node main`, it will throw errors like this:

```
ReferenceError: name is not defined
    at Engine.addTapeNode (/Users/rilut/typescript/node_modules/deeplearn/dist/engine.js:153:19)
    at /Users/rilut/typescript/node_modules/deeplearn/dist/engine.js:272:23
    at Ops.mean (/Users/rilut/typescript/node_modules/deeplearn/dist/ops/reduction_ops.js:90:16)
    at /Users/rilut/typescript/node_modules/deeplearn/dist/ops/operation.js:12:61
    at Object.Tracking.tidy (/Users/rilut/typescript/node_modules/deeplearn/dist/tracking.js:34:22)
    at Object.descriptor.value [as mean] (/Users/rilut/typescript/node_modules/deeplearn/dist/ops/operation.js:12:26)
    at forward (/Users/rilut/typescript/main.ts:18:16)
    at /Users/rilut/typescript/main.ts:34:22
    at /Users/rilut/typescript/node_modules/deeplearn/dist/engine.js:223:21
    at Object.Tracking.tidy (/Users/rilut/typescript/node_modules/deeplearn/dist/tracking.js:34:22)
```

If I add `console.log()` on the operation.js, it will show this:

```
ts-node main
randomNormal
rand
gather
zeros
mean
div
sum
zeros
ReferenceError: name is not defined
.........
```

**Comment by tafsiri** [comment]
Hi @rilut, we currently haven't spent much time trying deeplearn.js in node environments, we primarily target browser environments so you might have an easier time running this in the browser than in ts-node. I would suggest looking into the [starter project for typescript](https://github.com/PAIR-code/deeplearnjs/tree/master/starter/typescript) or something similar to get up an running with that.

I was able to get your code running in the browser but did run into another issue, we currently don't have gradients implemented for dl.gather. I added an issue to track that [here](https://github.com/PAIR-code/deeplearnjs/issues/813) but it would be a blocker for your code (for the backward pass).

**Comment by dsmilkov** [comment]
Thanks @rilut for filling this. We are about to release 0.5.1 where we improved the error message. I ran your example in the browser with deeplearn@HEAD and got: `Cannot compute gradient: gradient function not found for gather.` We have a separate issue #813 to add gradients for `gather`
